# Generated by Django 5.2 on 2026-03-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamuser',
            name='is_approved',
            field=models.BooleanField(default=None, null=True, verbose_name='Одобрено вступление'),
        ),
    ]
