# Generated by Django 5.2 on 2026-04-11 21:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_remove_equipment_unique_user_equipment'),
        ('materials', '0003_alter_material_share'),
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes_connections', to='materials.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Соединение схемы',
                'verbose_name_plural': 'Соединения схемы',
            },
        ),
        migrations.CreateModel(
            name='SchemeConnectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Индекс не может быть меньше 0.')], verbose_name='Индекс')),
                ('x', models.FloatField(default=0.0, verbose_name='X')),
                ('z', models.FloatField(default=0.0, verbose_name='Z')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes_connection_points', to='schemes.schemeconnection', verbose_name='Соединение')),
            ],
            options={
                'verbose_name': 'Соединение схемы',
                'verbose_name_plural': 'Соединения схемы',
            },
        ),
        migrations.CreateModel(
            name='SchemeEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0.0, verbose_name='X')),
                ('z', models.FloatField(default=0.0, verbose_name='Z')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes_equipments', to='equipments.equipment', verbose_name='Оборудование')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes_equipments', to='materials.material', verbose_name='Материал')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes_equipments', to='schemes.scheme', verbose_name='Схема')),
            ],
            options={
                'verbose_name': 'Оборудование схемы',
                'verbose_name_plural': 'Оборудования схемы',
            },
        ),
        migrations.CreateModel(
            name='SchemeEquipmentHole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes_equipment_holes', to='equipments.equipmenthole', verbose_name='Отверстие')),
                ('scheme_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes_equipment_holes', to='schemes.schemeequipment', verbose_name='Оборудование схемы')),
            ],
            options={
                'verbose_name': 'Отверстие оборудования схемы',
                'verbose_name_plural': 'Отверстие оборудования схемы',
            },
        ),
        migrations.AddField(
            model_name='schemeconnection',
            name='scheme_equipment_hole_end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes_connections_ends', to='schemes.schemeequipmenthole', verbose_name='Второе отверстие соединения'),
        ),
        migrations.AddField(
            model_name='schemeconnection',
            name='scheme_equipment_hole_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes_connections_starts', to='schemes.schemeequipmenthole', verbose_name='Первое отверстие соединения'),
        ),
    ]
