# Generated by Django 5.2 on 2026-04-11 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_schemeconnection_schemeconnectionpoint_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schemeconnectionpoint',
            options={'verbose_name': 'Точка соединения схемы', 'verbose_name_plural': 'Точки соединения схемы'},
        ),
    ]
