# Generated by Django 5.2 on 2026-06-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0003_alter_schemeconnectionpoint_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeconnection',
            name='r',
            field=models.FloatField(default=20.0, verbose_name='Радиус'),
        ),
    ]
