# Generated by Django 5.2 on 2026-03-25 19:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_global', models.BooleanField(default=False, verbose_name='Глобальный материал')),
                ('base_color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Введите цвет в формате HEX (#FFFFFF или #FFF)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Базовый цвет (HEX)')),
                ('reflectivity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Отражаемость не может быть меньше 0.'), django.core.validators.MaxValueValidator(1.0, message='Отражаемость не может превышать 1.')], verbose_name='Отражаемость')),
                ('transparency', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Прозрачность не может быть меньше 0.'), django.core.validators.MaxValueValidator(1.0, message='Прозрачность не может превышать 1.')], verbose_name='Прозрачность')),
                ('shininess', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Блестящесть не может быть меньше 0.'), django.core.validators.MaxValueValidator(1.0, message='Блестящесть не может превышать 1.')], verbose_name='Блестящесть')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
    ]
