# Generated by Django 5.2 on 2026-03-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='share',
            field=models.BooleanField(default=False, verbose_name='Глобальный материал'),
        ),
    ]
