# Generated by Django 5.2 on 2026-04-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='share',
            field=models.BooleanField(default=False, verbose_name='Поделиться с командой'),
        ),
    ]
