# Generated by Django 5.2 on 2026-04-05 11:41

import django.core.validators
import equipments.models.equipment_type
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название')),
                ('file', models.FileField(upload_to='equipment_types/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg']), equipments.models.equipment_type.validate_file_size])),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
            },
        ),
    ]
