# Generated by Django 5.2 on 2026-04-05 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
        ('models_3d', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_global', models.BooleanField(default=False, verbose_name='Глобальный материал')),
                ('share', models.BooleanField(default=False, verbose_name='Поделиться с командой')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='models_3d.model3d', verbose_name='Модель')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='equipments.equipmenttype', verbose_name='Тип')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
                'constraints': [models.UniqueConstraint(fields=('user', 'model', 'type'), name='unique_user_equipment')],
            },
        ),
    ]
