# Generated by Django 5.2 on 2026-04-05 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentHole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('normal_x', models.FloatField(blank=True, default=0.0, verbose_name='Вектор нормали по X')),
                ('normal_y', models.FloatField(blank=True, default=0.0, verbose_name='Вектор нормали по Y')),
                ('normal_z', models.FloatField(blank=True, default=0.0, verbose_name='Вектор нормали по Z')),
                ('offset_x', models.FloatField(blank=True, default=0.0, verbose_name='Смещение по X')),
                ('offset_y', models.FloatField(blank=True, default=0.0, verbose_name='Смещение по Y')),
                ('offset_z', models.FloatField(blank=True, default=0.0, verbose_name='Смещение по Z')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holes', to='equipments.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Отверстие оборудования',
                'verbose_name_plural': 'Отверстия оборудования',
            },
        ),
    ]
