# Generated by Django 5.2 on 2026-04-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_equipmenthole'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
    ]
