# Generated by Django 5.2 on 2026-04-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_equipmenttype_is_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='equipment',
            name='unique_user_equipment',
        ),
    ]
