# Generated by Django 5.2.9 on 2026-02-09 19:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Сборка',
                'verbose_name_plural': 'Сборки',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('density', models.FloatField(validators=[django.core.validators.MinValueValidator(0.001, message='Плотность должна быть больше 0'), django.core.validators.MaxValueValidator(50, message='Плотность не может превышать 30000 кг/м³')], verbose_name='Плотность')),
                ('base_color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Введите цвет в формате HEX (#FFFFFF или #FFF)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Базовый цвет (HEX)')),
                ('reflectivity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Отражаемость не может быть меньше 0'), django.core.validators.MaxValueValidator(1.0, message='Отражаемость не может превышать 1')], verbose_name='Отражаемость')),
                ('transparency', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Прозрачность не может быть меньше 0'), django.core.validators.MaxValueValidator(1.0, message='Прозрачность не может превышать 1')], verbose_name='Прозрачность')),
                ('shininess', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Блестящесть не может быть меньше 0'), django.core.validators.MaxValueValidator(1.0, message='Блестящесть не может превышать 1')], verbose_name='Блестящесть')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model_constructor.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
            },
        ),
        migrations.CreateModel(
            name='CoordinateSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('offset_x', models.FloatField(verbose_name='Координата X')),
                ('offset_y', models.FloatField(verbose_name='Координата Y')),
                ('offset_z', models.FloatField(verbose_name='Координата Z')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыто')),
                ('assembly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_constructor.assembly', verbose_name='Сборка')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_constructor.part', verbose_name='Деталь')),
            ],
            options={
                'verbose_name': 'Система координат',
                'verbose_name_plural': 'Системы координат',
            },
        ),
        migrations.CreateModel(
            name='AssemblyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название детали в сборке')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('offset_x', models.FloatField(default=0.0, verbose_name='Смещение X')),
                ('offset_y', models.FloatField(default=0.0, verbose_name='Смещение Y')),
                ('offset_z', models.FloatField(default=0.0, verbose_name='Смещение Z')),
                ('rotation_x', models.FloatField(default=0.0, verbose_name='Поворот X')),
                ('rotation_y', models.FloatField(default=0.0, verbose_name='Поворот Y')),
                ('rotation_z', models.FloatField(default=0.0, verbose_name='Поворот Z')),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model_constructor.assembly', verbose_name='Сборка')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model_constructor.part', verbose_name='Деталь')),
            ],
            options={
                'verbose_name': 'Деталь в сборке',
                'verbose_name_plural': 'Детали в сборках',
            },
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('normal_x', models.FloatField(verbose_name='Вектор нормали по X')),
                ('normal_y', models.FloatField(verbose_name='Вектор нормали по Y')),
                ('normal_z', models.FloatField(verbose_name='Вектор нормали по Z')),
                ('offset_x', models.FloatField(blank=True, null=True, verbose_name='Смещение по X')),
                ('offset_y', models.FloatField(blank=True, null=True, verbose_name='Смещение по Y')),
                ('offset_z', models.FloatField(blank=True, null=True, verbose_name='Смещение по Z')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыто')),
                ('assembly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_constructor.assembly', verbose_name='Сборка')),
                ('coordinate_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_constructor.coordinatesystem', verbose_name='Система координат')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_constructor.part', verbose_name='Деталь')),
            ],
            options={
                'verbose_name': 'Плоскость',
                'verbose_name_plural': 'Плоскости',
            },
        ),
        migrations.AddConstraint(
            model_name='coordinatesystem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assembly__isnull', True), ('part__isnull', False)), models.Q(('assembly__isnull', False), ('part__isnull', True)), _connector='OR'), name='only_one_foreign_key_cs'),
        ),
        migrations.AddConstraint(
            model_name='assemblypart',
            constraint=models.UniqueConstraint(fields=('assembly', 'name'), name='unique_assembly_part_name'),
        ),
        migrations.AddConstraint(
            model_name='plane',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assembly__isnull', True), ('coordinate_system__isnull', True), ('part__isnull', False)), models.Q(('assembly__isnull', True), ('coordinate_system__isnull', False), ('part__isnull', True)), models.Q(('assembly__isnull', False), ('coordinate_system__isnull', True), ('part__isnull', True)), _connector='OR'), name='only_one_foreign_key'),
        ),
        migrations.AddConstraint(
            model_name='plane',
            constraint=models.CheckConstraint(condition=models.Q(('coordinate_system__isnull', False), models.Q(('coordinate_system__isnull', True), ('offset_x__isnull', False), ('offset_y__isnull', False), ('offset_z__isnull', False)), _connector='OR'), name='offsets_required_without_cs'),
        ),
    ]
