# Generated by Django 5.2 on 2026-03-25 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('model_constructor', '0002_remove_material_density'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material', verbose_name='Материал'),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
