# Generated by Django 5.2 on 2026-04-05 13:56

import django.core.validators
import django.db.models.deletion
import models_3d.models.model_3d
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название')),
                ('file', models.FileField(upload_to='models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['fbx']), models_3d.models.model_3d.validate_file_size_20])),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_global', models.BooleanField(default=False, verbose_name='Глобальный материал')),
                ('share', models.BooleanField(default=False, verbose_name='Поделиться с командой')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
    ]
