# Generated by Django 5.2 on 2026-04-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_3d', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='depth',
            field=models.FloatField(default=1.0, help_text='Размер по оси Z в метрах', verbose_name='Глубина (Z)'),
        ),
        migrations.AddField(
            model_name='model3d',
            name='height',
            field=models.FloatField(default=1.0, help_text='Размер по оси Y в метрах', verbose_name='Высота (Y)'),
        ),
        migrations.AddField(
            model_name='model3d',
            name='width',
            field=models.FloatField(default=1.0, help_text='Размер по оси X в метрах', verbose_name='Ширина (X)'),
        ),
    ]
